var searchData=
[
  ['compression_68',['Compression',['../namespaceSCM_1_1SwissArmyKnife_1_1Compression.html',1,'SCM::SwissArmyKnife']]],
  ['extensions_69',['Extensions',['../namespaceSCM_1_1SwissArmyKnife_1_1Extensions.html',1,'SCM::SwissArmyKnife']]],
  ['files_70',['Files',['../namespaceSCM_1_1SwissArmyKnife_1_1Files.html',1,'SCM::SwissArmyKnife']]],
  ['samevaluedictionary_71',['SameValueDictionary',['../classSCM_1_1SwissArmyKnife_1_1TestUtils_1_1SameValueDictionary.html#aedaaaaa2c2eb864bb551e2f627e768c4',1,'SCM.SwissArmyKnife.TestUtils.SameValueDictionary.SameValueDictionary()'],['../classSCM_1_1SwissArmyKnife_1_1TestUtils_1_1SameValueDictionary.html',1,'SameValueDictionary&lt; TKey, TValue &gt;']]],
  ['samevaluedictionary_2ecs_72',['SameValueDictionary.cs',['../SameValueDictionary_8cs.html',1,'']]],
  ['scm_73',['SCM',['../namespaceSCM.html',1,'']]],
  ['select_3c_20tin_2c_20tout_20_3e_74',['Select&lt; TIn, TOut &gt;',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a3cf67ffa5d65e2bd8b51db10375195ee',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; List&lt; TIn &gt;&gt; task, Func&lt; TIn, TOut &gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a280e2eca71715bb579de5e989792a382',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; TIn &gt; task, Func&lt; TIn, TOut &gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a0c894ab9829a0f35fcd1b2ad1b13b3a6',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; IEnumerable&lt; TIn &gt;&gt; task, Func&lt; TIn, TOut &gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a7f26be923e935de725a122d25f7c51d9',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; TIn[]&gt; task, Func&lt; TIn, TOut &gt; selector)']]],
  ['selectmany_3c_20tin_2c_20tout_20_3e_75',['SelectMany&lt; TIn, TOut &gt;',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#aaec4d98d02da10788ab49609ee563bac',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.SelectMany&lt; TIn, TOut &gt;(this Task&lt; TIn[]&gt; task, Func&lt; TIn, IEnumerable&lt; TOut &gt;&gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a241520bef59a29a1950420b073ffbad8',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.SelectMany&lt; TIn, TOut &gt;(this Task&lt; List&lt; TIn &gt;&gt; task, Func&lt; TIn, IEnumerable&lt; TOut &gt;&gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a90e1c6df172d725691fbe10b3ca9ebe9',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.SelectMany&lt; TIn, TOut &gt;(this Task&lt; IEnumerable&lt; TIn &gt;&gt; task, Func&lt; TIn, IEnumerable&lt; TOut &gt;&gt; selector)']]],
  ['selectvalues_3c_20tkey_2c_20toldvalue_2c_20tnewvalue_20_3e_76',['SelectValues&lt; TKey, TOldValue, TNewValue &gt;',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1DictionaryExtensions.html#a5bf380d9e734d1410db9be5ce8b773ad',1,'SCM::SwissArmyKnife::Extensions::DictionaryExtensions']]],
  ['streamextensions_77',['StreamExtensions',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1StreamExtensions.html',1,'SCM::SwissArmyKnife::Extensions']]],
  ['streamextensions_2ecs_78',['StreamExtensions.cs',['../StreamExtensions_8cs.html',1,'']]],
  ['stringextensions_79',['StringExtensions',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1StringExtensions.html',1,'SCM::SwissArmyKnife::Extensions']]],
  ['stringextensions_2ecs_80',['StringExtensions.cs',['../StringExtensions_8cs.html',1,'']]],
  ['swissarmyknife_81',['SwissArmyKnife',['../index.html',1,'(Global Namespace)'],['../namespaceSCM_1_1SwissArmyKnife.html',1,'SCM.SwissArmyKnife']]],
  ['testutils_82',['TestUtils',['../namespaceSCM_1_1SwissArmyKnife_1_1TestUtils.html',1,'SCM::SwissArmyKnife']]]
];
