var searchData=
[
  ['compression_52',['Compression',['../namespaceSCM_1_1SwissArmyKnife_1_1Compression.html',1,'SCM::SwissArmyKnife']]],
  ['extensions_53',['Extensions',['../namespaceSCM_1_1SwissArmyKnife_1_1Extensions.html',1,'SCM::SwissArmyKnife']]],
  ['files_54',['Files',['../namespaceSCM_1_1SwissArmyKnife_1_1Files.html',1,'SCM::SwissArmyKnife']]],
  ['scm_55',['SCM',['../namespaceSCM.html',1,'']]],
  ['select_3c_20tin_2c_20tout_20_3e_56',['Select&lt; TIn, TOut &gt;',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a280e2eca71715bb579de5e989792a382',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; TIn &gt; task, Func&lt; TIn, TOut &gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a0c894ab9829a0f35fcd1b2ad1b13b3a6',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; IEnumerable&lt; TIn &gt;&gt; task, Func&lt; TIn, TOut &gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a7f26be923e935de725a122d25f7c51d9',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; TIn[]&gt; task, Func&lt; TIn, TOut &gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a3cf67ffa5d65e2bd8b51db10375195ee',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.Select&lt; TIn, TOut &gt;(this Task&lt; List&lt; TIn &gt;&gt; task, Func&lt; TIn, TOut &gt; selector)']]],
  ['selectmany_3c_20tin_2c_20tout_20_3e_57',['SelectMany&lt; TIn, TOut &gt;',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#aaec4d98d02da10788ab49609ee563bac',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.SelectMany&lt; TIn, TOut &gt;(this Task&lt; TIn[]&gt; task, Func&lt; TIn, IEnumerable&lt; TOut &gt;&gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a90e1c6df172d725691fbe10b3ca9ebe9',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.SelectMany&lt; TIn, TOut &gt;(this Task&lt; IEnumerable&lt; TIn &gt;&gt; task, Func&lt; TIn, IEnumerable&lt; TOut &gt;&gt; selector)'],['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1FluentTaskExtensions.html#a241520bef59a29a1950420b073ffbad8',1,'SCM.SwissArmyKnife.Extensions.FluentTaskExtensions.SelectMany&lt; TIn, TOut &gt;(this Task&lt; List&lt; TIn &gt;&gt; task, Func&lt; TIn, IEnumerable&lt; TOut &gt;&gt; selector)']]],
  ['selectvalues_3c_20tkey_2c_20toldvalue_2c_20tnewvalue_20_3e_58',['SelectValues&lt; TKey, TOldValue, TNewValue &gt;',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1DictionaryExtensions.html#a5bf380d9e734d1410db9be5ce8b773ad',1,'SCM::SwissArmyKnife::Extensions::DictionaryExtensions']]],
  ['streamextensions_59',['StreamExtensions',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1StreamExtensions.html',1,'SCM::SwissArmyKnife::Extensions']]],
  ['streamextensions_2ecs_60',['StreamExtensions.cs',['../StreamExtensions_8cs.html',1,'']]],
  ['stringextensions_61',['StringExtensions',['../classSCM_1_1SwissArmyKnife_1_1Extensions_1_1StringExtensions.html',1,'SCM::SwissArmyKnife::Extensions']]],
  ['stringextensions_2ecs_62',['StringExtensions.cs',['../StringExtensions_8cs.html',1,'']]],
  ['swissarmyknife_63',['SwissArmyKnife',['../index.html',1,'(Global Namespace)'],['../namespaceSCM_1_1SwissArmyKnife.html',1,'SCM.SwissArmyKnife']]]
];
